# 异常处理

异常是指程序运行时发生的特殊情况，比如除以零

异常提供了一种转移程序控制权的方法

## **`try`、`catch`、`throw`**

异常处理涉及三个关键字

`try`、`catch`、`throw`

`throw`用于抛出异常

```c++
double division(int a, int b)
{
   if( b == 0 )
   {
      throw "Division by zero condition!";
   }
   return (a/b);
}
```

`catch`和`try`用于捕获异常，且可以通过`catch`括号内的异常声明类型决定捕获的异常类型

```c++
#include <iostream>
using namespace std;
 
double division(int a, int b)
{
   if( b == 0 )
   {
      throw "Division by zero condition!";
   }
   return (a/b);
}
 
int main ()
{
   int x = 50;
   int y = 0;
   double z = 0;
 
   try {
     z = division(x, y);
     cout << z << endl;
   }catch (const char* msg) {
     cerr << msg << endl;
   }
 
   return 0;
}
```

示例代码在运行时会在控制台抛出异常信息

## c++标准库的异常

c++在\<exception\>中提供了一系列标准的异常

![](D:\OneDrive\学校\大学\QG工作室图形组\2023训练营\2023暑期训练营\Week 2\Markdown Images\异常处理.png)

| 异常                    | 描述                                                         |
| :---------------------- | :----------------------------------------------------------- |
| `std::exception`        | 该异常是所有标准 C++ 异常的父类。                            |
| `std::bad_alloc`        | 该异常可以通过 `**new**` 抛出。                              |
| `std::bad_cast`         | 该异常可以通过 `**dynamic_cast**` 抛出。                     |
| `std::bad_typeid`       | 该异常可以通过` **typeid** `抛出。                           |
| `std::bad_exception`    | 这在处理 C++ 程序中无法预期的异常时非常有用。                |
| `std::logic_error`      | 理论上可以通过读取代码来检测到的异常。                       |
| `std::domain_error`     | 当使用了一个无效的数学域时，会抛出该异常。                   |
| `std::invalid_argument` | 当使用了无效的参数时，会抛出该异常。                         |
| `std::length_error`     | 当创建了太长的 `std::string` 时，会抛出该异常。              |
| `std::out_of_range`     | 该异常可以通过方法抛出，例如 `std::vector` 和 `std::bitset<>::operator[]()`。 |
| `std::runtime_error`    | 理论上不可以通过读取代码来检测到的异常。                     |
| `std::overflow_error`   | 当发生数学上溢时，会抛出该异常。                             |
| `std::range_error`      | 当尝试存储超出范围的值时，会抛出该异常。                     |
| `std::underflow_error`  | 当发生数学下溢时，会抛出该异常。                             |

也可以通过继承和重载**`exception`**来定义新的异常